version: "3.9"

services:
  backend:
    image: "ghcr.io/ayrron/tp-back_info-910:main"

    ports:
      - 8080:80

    networks:
      - demonet
    healthcheck:
      test: ["CMD", "/usr/bin/curl", "--head", "-sSf", "http://localhost"]
      interval: 15s
      timeout: 15s
      retries: 6
      start_period: 30s
      start_interval: 5s


  frontend:
    image: "ghcr.io/mathisfeltrin/info910-f1-leaderboard-frontend:latest"
    ports:
      - 80:80
    networks:
      - demonet
    healthcheck:
      test: ["CMD", "/usr/bin/curl", "--head", "-sSf", "http://localhost"]
      interval: 15s
      timeout: 15s
      retries: 6
      start_period: 30s
      start_interval: 5s

networks:
  demonet:
